---
- name: Build Local Backup Dir Path
  ansible.builtin.include_tasks: path.yaml
  when: data_store.scm.origin is not defined

- name: Include retrieve tasks
  ansible.builtin.include_tasks: retrieve.yaml
  when: data_store['scm']['origin'] is defined
  run_once: true

- name: Get scm url
  ansible.builtin.set_fact:
    network_backup_path_root: "{{ role_path }}/{{  data_store.scm.origin.url.split('/')[-1] }}"
  when: data_store['scm']['origin'] is defined

- name: Get file name
  ansible.builtin.set_fact:
    network_backup_path: "{{ network_backup_path_root }}/{{  data_store.scm.origin.path }}"
  when: data_store['scm']['origin'] is defined

- name: Get file name
  ansible.builtin.set_fact:
    network_backup_filename: "{{  data_store.scm.origin.filename }}"
  when: data_store['scm']['origin'] is defined


- name: Include tasks
  ansible.builtin.include_tasks: network.yaml

- name: Include build tasks
  ansible.builtin.include_tasks: publish.yaml
  when: data_store.scm.origin is defined
  run_once: true
