---
- name: Set default path for backup
  ansible.builtin.set_fact:
    network_backup_path: "."
  when: data_store['local'] is not defined

- name: Set local backup path
  ansible.builtin.set_fact:
    network_backup_path: "{{ data_store['local']['path'] }}"
  when: data_store['local'] is defined

- name: Set local backup path
  ansible.builtin.set_fact:
    network_backup_filename: "{{ data_store['local']['filename'] }}"
  when: data_store['local'] is defined
