---
- name: Full Backup Play
  hosts: rtr1
  gather_facts: false
  vars:
    GH_REPO: "https://github.com/rohitthakur2590/network_automation_backups"
  tasks:
    - name: Perform pre-run checks
      ansible.builtin.include_tasks:
        file: ./pre_remote_validation.yaml

    - name: Network Backup and Resource Manager
      ansible.builtin.include_role:
        name: network.backup.run
      vars:
        operation: backup
        data_store:
          scm:
            origin:
              url: "{{ GH_REPO }}"
              token: "{{ VALIDATED_RO_KEY }}"
              user:
                name: rohitthakur2590
                email: rohitthakur2590@outlook.com
